# Generated by Django 3.2.5 on 2021-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggednotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='note_rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
