# Generated by Django 3.2.5 on 2021-07-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggednotes', '0002_section_note_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='rank',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
