# Generated by Django 3.2.5 on 2021-08-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggednotes', '0005_auto_20210801_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default='', max_length=19999),
        ),
        migrations.AlterField(
            model_name='note',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='section',
            name='note_rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='tag_rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
