# Generated by Django 3.2.5 on 2021-08-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggednotes', '0007_auto_20210802_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(max_length=51),
        ),
    ]
